groups:
  md_5:
  - admin
disabled_commands:
- disabledcommandhere
player_limit: -1
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
listeners:
- query_port: 25565
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  forced_hosts: {}
  ping_passthrough: false
  default_server: defaultserver
  bind_local_address: true
  fallback_server: defaultserver
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: false
timeout: 30000
connection_throttle: -1
servers:
  defaultserver:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25565
    restricted: false
ip_forward: true
online_mode: true
